#! /bin/bash

HOST=$1
DBNAME=$2
USER=$3

psql -h $HOST -d $DBNAME -U $USER \
     -c `echo ../src/server/db/create_db.sql`
     
psql -h $HOST -d $DBNAME -U $USER \
     -c `echo ../src/server/db/create_tables.sql`

psql -h $HOST -d $DBNAME -U $USER \
     -c `echo ../src/server/db/create_procedures.sql`
